const SINGLETON_LABEL_VOCABULARY_PROPERTY_NAMES = [
	"animation-delay",
	"animation-direction",
	"animation-duration",
	"animation-fill-mode",
	"animation-iteration-count",
	"animation-name",
	"animation-play-state",
	"animation-timing-function",
	"aspect-ratio",
	"background-image",
	"background-origin",
	"background-clip",
	"border-block-end",
	"border-block-start",
	"border-end-end-radius",
	"border-end-start-radius",
	"border-inline-end",
	"border-inline-start",
	"border-start-end-radius",
	"border-start-start-radius",
	"clip-path",
	"column-count",
	"column-width",
	"corner-bottom-left-shape",
	"corner-bottom-right-shape",
	"corner-end-end-shape",
	"corner-end-start-shape",
	"corner-start-end-shape",
	"corner-start-start-shape",
	"corner-top-left-shape",
	"corner-top-right-shape",
	"font-variant-caps",
	"gap",
	"grid-auto-flow",
	"offset-path",
	"place-content",
	"place-items",
	"place-self",
	"position-try",
	"position-try-fallbacks",
	"shape-outside",
	"size",
	"text-box-edge",
	"text-box-trim",
	"text-emphasis-color",
	"text-emphasis-style",
	"text-wrap",
	"text-wrap-mode",
	"white-space-collapse",
] as const;

export const SINGLETON_LABEL_VOCABULARY_PROPERTIES = new Set<string>(SINGLETON_LABEL_VOCABULARY_PROPERTY_NAMES);

export function isSingletonLabelVocabularyProperty(propertyName: string): boolean {
	return SINGLETON_LABEL_VOCABULARY_PROPERTIES.has(propertyName);
}
